/* eslint-disable react/no-unescaped-entities */

import ContactForm from "../components/ContactComponents/ContactForm";
import { Metadata } from "next";
import ContentContactPage from "../components/ContactComponents/ContentContactPage";

export const metadata: Metadata = {
  title: "Formulaire de contact - Portfolio Bahoz",
  description: "Generated by create next app",
};

export default function Contact() {
  return (
    <div className="py-12">
      <ContentContactPage />
      <ContactForm />
    </div>
  );
}
