import React from "react";
import { Metadata } from "next";
import ContentPortfolioPage from "../components/PortfolioComponents/ContentPortfolioPage";

export const metadata: Metadata = {
  title: "Galerie des projets - Portfolio Bahoz",
  description: "Generated by create next app",
};

export default function Portfolio() {
  return <ContentPortfolioPage />;
}
